name: Design patterns

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install --with dev

      - name: flake8 lint
        run: poetry run flake8 patterns

      - name: mypy type check
        run: poetry run mypy patterns

      - name: Test with pytest
        run: poetry run pytest
